name: Run Smoke Tests on Push to Master

on:
  push:
    branches:
      - master

jobs:
  run-smoke-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18' # Change to 11 or 21 if needed

      - name: Run Smoke Tests with Maven
        run: mvn test -Dgroups=smoke
